# Generated by Django 3.0.14 on 2022-08-07 10:29

from django.db import migrations, models
import django.db.models.deletion
import leads.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('phone1', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس۲')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('expertise', models.CharField(max_length=100, verbose_name='تخصص')),
                ('region', models.CharField(max_length=100, verbose_name='مناطق کاری')),
                ('time_shift', models.CharField(max_length=100, verbose_name=' شیفت کاری22')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('weight', models.FloatField(blank=True, default=0.2, null=True, verbose_name='کارمزد')),
                ('balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودی حساب')),
                ('activation_status', models.IntegerField(choices=[(1, 'active'), (2, 'deactive'), (3, 'ban')], default=1, verbose_name='وضعیت')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=leads.models.handle_upload_Madarek)),
                ('file', models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_Madarek)),
            ],
            options={
                'verbose_name': 'تکنسین',
                'verbose_name_plural': 'تکنسین',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='شماره تماس مشتری')),
                ('customer_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مشتری')),
                ('problem', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('پنچری', 'پنچری'), ('دینام', 'دینام'), ('برق', 'برق'), ('تسمه', 'تسمه'), ('روشن نمی شود', 'روشن نمی شود'), ('مشکل استارت', 'مشکل استارت'), ('بدنه', 'بدنه'), ('ترمز', 'ترمز')], max_length=55, null=True, verbose_name='مشکل')),
                ('motor_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل موتور')),
                ('address', models.CharField(max_length=1500, verbose_name='آدرس')),
                ('total_price_cusotmer', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه نهایی پرداخت شده توسط مشتری')),
                ('total_price_agent', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه نهایی پرداخت شده توسط تکنسین')),
                ('technician_messeg', models.BooleanField(default=False, verbose_name='ارسال پیامک به تکنسین')),
                ('customer_messeg', models.BooleanField(default=False, verbose_name='ارسال پیامک به مشتری')),
                ('grade', models.SmallIntegerField(blank=True, null=True, verbose_name='امتیاز عملکرد')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('در حال انجام', 'در حال انجام'), ('انجام شد', 'انجام شد'), ('در آستانه کنسلی', 'در آستانه کنسلی'), ('کنسلی قطعی', 'کنسلی قطعی')], default='در حال انجام', max_length=15, verbose_name='وضعیت سفارش')),
                ('transaction_status', models.CharField(default='تسویه نشده', max_length=32, verbose_name='وضعیت تسویه')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.Agent', verbose_name='تکنسین')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='دریافتی کل')),
                ('company_amount', models.PositiveIntegerField(verbose_name='سهم شرکت')),
                ('category', models.CharField(choices=[('دریافتی از سفارش', 'دریافتی از سفارش'), ('واریزی توسط تکنسین', 'واریزی توسط تکنسین')], max_length=32, verbose_name='عنوان')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='کامنت')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.Lead', verbose_name='سفارش')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.Agent', verbose_name='تکنسین')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('groupId', models.IntegerField(blank=True, null=True, verbose_name='شناسه پیامک')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت پیامک')),
                ('reciever', models.IntegerField(choices=[(1, 'مشتری'), (2, 'تکنسین')], verbose_name='دریافت کننده')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_price_cusotmer', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه نهایی پرداخت شده توسط مشتری')),
                ('total_price_agent', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه نهایی پرداخت شده توسط تکنسین')),
                ('grade', models.SmallIntegerField(blank=True, null=True, verbose_name='امتیاز عملکرد')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.Lead')),
            ],
            options={
                'verbose_name': 'پیگیری',
                'verbose_name_plural': 'پیگیری',
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.Agent')),
            ],
        ),
    ]
