# Generated by Django 3.0.14 on 2022-08-07 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='problem',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='مشکل'),
            preserve_default=False,
        ),
    ]
