# Generated by Django 3.0.14 on 2022-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20220807_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='problem',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='مشکل'),
        ),
    ]
