# Generated by Django 3.0.14 on 2022-08-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20220807_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='time_shift',
            field=models.CharField(max_length=100, verbose_name=' شیفت کاری'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='total_price_agent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='اجرت نهایی پرداخت شده توسط تکنسین'),
        ),
    ]
