# Generated by Django 3.0.14 on 2022-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20220812_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='groupId',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='شناسه پیامک'),
        ),
    ]
