# Generated by Django 4.2.1 on 2023-05-16 11:14

import EmdadUser.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_users_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technecian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('commission', models.FloatField(default=0.2, verbose_name='کارمزد')),
                ('balance', models.IntegerField(default=0, verbose_name='موجودی حساب')),
                ('expertise', models.CharField(max_length=100, verbose_name='تخصص')),
                ('time_shift', models.CharField(max_length=100, verbose_name=' شیفت کاری')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('activation_status', models.IntegerField(choices=[(1, 'فعال'), (2, 'غیرفعال'), (3, 'تعلیق')], default=1, verbose_name='وضعیت')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=EmdadUser.models.Technecian_handle_upload)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EmdadUser.customuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارشناس',
                'verbose_name_plural': 'کارشناس',
            },
        ),
        migrations.CreateModel(
            name='Tech_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام فایل')),
                ('file', models.FileField(blank=True, null=True, upload_to=EmdadUser.models.Technecian_handle_upload)),
                ('tech_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EmdadUser.technecian', verbose_name='کارشناس')),
            ],
            options={
                'verbose_name': 'مدارک',
                'verbose_name_plural': 'مدارک',
            },
        ),
    ]
