# Generated by Django 4.2.1 on 2023-05-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmdadUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technecian',
            name='expertise',
        ),
    ]
