# Generated by Django 4.2.1 on 2023-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmdadUser', '0002_remove_technecian_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='raw_password',
            field=models.CharField(default=12121, max_length=6, verbose_name='گذرواژه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technecian',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='بدهی '),
        ),
    ]
