# Generated by Django 4.2.1 on 2023-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmdadUser', '0003_customuser_raw_password_alter_technecian_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='raw_password',
            field=models.CharField(max_length=6, verbose_name=' گذرواژه خام'),
        ),
        migrations.AlterField(
            model_name='technecian',
            name='address',
            field=models.CharField(max_length=320, verbose_name='آدرس'),
        ),
    ]
