# Generated by Django 4.2.1 on 2023-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmdadUser', '0004_alter_customuser_raw_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تماس'),
        ),
    ]
