# Generated by Django 4.2.1 on 2023-06-03 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmdadUser', '0006_alter_technecian_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technecian',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
