# Generated by Django 3.2.19 on 2023-08-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmdadUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='techdoc',
            old_name='tech_id',
            new_name='technician',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='user_id',
            new_name='user',
        ),
    ]
