# Generated by Django 3.2.19 on 2023-08-18 21:15

import apps.Transaction.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmdadUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('amount', models.PositiveIntegerField(verbose_name='amount transaction')),
                ('doc', models.FileField(blank=True, null=True, upload_to=apps.Transaction.models.transaction_handle_upload)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='explanation')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EmdadUser.technician')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'Transaction',
            },
        ),
    ]
