# Generated by Django 3.2.19 on 2023-08-18 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Emdad', '0001_initial'),
        ('EmdadUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='customer call number')),
                ('customer_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='customer name')),
                ('status', models.CharField(choices=[('w', 'working'), ('d', 'done'), ('c', 'cancellation'), ('cc', 'canceled')], default='w', max_length=15, verbose_name="order's status")),
                ('grade', models.SmallIntegerField(blank=True, default=5, null=True, verbose_name='grade')),
                ('wage', models.PositiveIntegerField(default=0, verbose_name='wage')),
                ('commission', models.PositiveIntegerField(blank=True, null=True, verbose_name='commission')),
                ('expanse', models.PositiveIntegerField(default=0, verbose_name='expenses')),
                ('total_price_cusotmer', models.PositiveIntegerField(blank=True, null=True, verbose_name='The final cost paid by the customer')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='explanation')),
                ('motors', models.ManyToManyField(to='Emdad.Motor', verbose_name='motors')),
                ('services', models.ManyToManyField(to='Emdad.Service', verbose_name='services')),
                ('technecian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EmdadUser.technician')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True, null=True, verbose_name='number')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='explanation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Emdad.product')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='explanation')),
                ('total_price_cusotmer', models.PositiveIntegerField(blank=True, null=True, verbose_name='')),
                ('total_wage_agent', models.PositiveIntegerField(blank=True, null=True, verbose_name='total cost paid by customer')),
                ('total_expanse_agent', models.PositiveIntegerField(blank=True, null=True, verbose_name='total wage paid, declered by technician')),
                ('grade', models.SmallIntegerField(blank=True, null=True, verbose_name='grade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='Order.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'followup',
                'verbose_name_plural': 'followups',
                'db_table': 'Followup',
            },
        ),
        migrations.AddConstraint(
            model_name='orderproduct',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_product'),
        ),
    ]
