# Generated by Django 3.2.19 on 2023-08-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='technecian',
            new_name='technician',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('working', 'working'), ('done', 'done'), ('cancellation', 'cancellation'), ('canceled', 'canceled')], default='working', max_length=15, verbose_name='order status'),
        ),
    ]
