# Generated by Django 3.0.14 on 2022-08-12 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='زمان')),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار')),
                ('comment', models.CharField(max_length=320, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'خرج کردها',
                'verbose_name_plural': 'خرج کردها',
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='زمان')),
                ('comment', models.TextField(verbose_name='عنوان')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('status', models.CharField(choices=[('در حال پیگیری', 'در حال پیگیری'), ('پیگیری شد', 'پیگیری شد')], default='در حال پیگیری', max_length=32, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'پیگیری ها',
                'verbose_name_plural': 'پیگیری ها',
            },
        ),
    ]
