# Generated by Django 4.2.1 on 2023-05-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='کمپانی')),
                ('brand', models.CharField(max_length=150, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='مدل')),
                ('year', models.CharField(blank=True, max_length=5, null=True, verbose_name='سال ساخت')),
                ('engine_type', models.IntegerField(choices=[(1, 'انژکتور'), (2, 'کاربراتور')], default=1, verbose_name='نوع موتور')),
            ],
            options={
                'verbose_name': 'موتور',
                'verbose_name_plural': 'موتور',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام قطعه')),
            ],
            options={
                'verbose_name': 'لوازم و قطعات',
                'verbose_name_plural': 'لوازم و قطعات',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='شهر')),
                ('area', models.CharField(max_length=150, verbose_name='منطقه یا ناحیه')),
                ('activation_status', models.IntegerField(choices=[(1, 'فعال'), (2, 'غیرفعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مناطق تحت پوشش',
                'verbose_name_plural': 'مناطق تحت پوشش',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام سرویس')),
                ('min_price', models.IntegerField(default=250000, verbose_name='کمینه قیمت')),
                ('max_price', models.IntegerField(default=250000, verbose_name='بیشینه قیمت')),
                ('activation_status', models.IntegerField(choices=[(1, 'فعال'), (2, 'غیرفعال')], default=1, verbose_name='وضعیت')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
