# Generated by Django 4.2.1 on 2023-05-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmdadUser', '0001_initial'),
        ('Emdad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='technecians',
            field=models.ManyToManyField(to='EmdadUser.technecian'),
        ),
        migrations.AddField(
            model_name='region',
            name='technecians',
            field=models.ManyToManyField(to='EmdadUser.technecian'),
        ),
        migrations.AddField(
            model_name='motor',
            name='technecians',
            field=models.ManyToManyField(to='EmdadUser.technecian'),
        ),
    ]
