# Generated by Django 3.2.19 on 2023-08-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmdadUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of product')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of service')),
                ('min_price', models.IntegerField(default=250000, verbose_name='minimum price')),
                ('max_price', models.IntegerField(default=250000, verbose_name='maximum price')),
                ('activation_status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1, verbose_name='status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='explanation')),
                ('technecians', models.ManyToManyField(blank=True, null=True, to='EmdadUser.Technician')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='city')),
                ('area', models.CharField(max_length=150, verbose_name='area')),
                ('activation_status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1, verbose_name='status')),
                ('technecians', models.ManyToManyField(blank=True, null=True, to='EmdadUser.Technician')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='company')),
                ('brand', models.CharField(max_length=150, verbose_name='brand')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='model')),
                ('year', models.CharField(blank=True, max_length=5, null=True, verbose_name='year of construction')),
                ('engine_type', models.IntegerField(choices=[(1, 'injector'), (2, 'carburetoer')], default=1, verbose_name='engine type')),
                ('technecians', models.ManyToManyField(blank=True, null=True, to='EmdadUser.Technician')),
            ],
            options={
                'verbose_name': 'motor',
                'verbose_name_plural': 'motors',
                'db_table': 'Motor',
            },
        ),
    ]
