# Generated by Django 4.2.1 on 2023-05-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmdadUser', '0001_initial'),
        ('Emdad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('location', models.CharField(max_length=100, verbose_name='آدرس')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='شماره تماس مشتری')),
                ('customer_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مشتری')),
                ('status', models.CharField(choices=[('در حال انجام', 'در حال انجام'), ('انجام شد', 'انجام شد'), ('در آستانه کنسلی', 'در آستانه کنسلی'), ('کنسل', 'کنسل')], default='در حال انجام', max_length=15, verbose_name='وضعیت سفارش')),
                ('grade', models.SmallIntegerField(blank=True, default=5, null=True, verbose_name='امتیاز عملکرد')),
                ('wage', models.PositiveIntegerField(default=0, verbose_name='اجرت')),
                ('expanse', models.PositiveIntegerField(default=0, verbose_name='خرجکرد')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('motors', models.ManyToManyField(to='Emdad.motor')),
                ('services', models.ManyToManyField(to='Emdad.service')),
                ('technecian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EmdadUser.technecian')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش',
            },
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Emdad.product')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('total_price_cusotmer', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه نهایی پرداخت شده توسط مشتری')),
                ('total_wage_agent', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه نهایی پرداخت شده توسط تکنسین')),
                ('total_expanse_agent', models.PositiveIntegerField(blank=True, null=True, verbose_name='اجرت نهایی پرداخت شده توسط تکنسین')),
                ('grade', models.SmallIntegerField(blank=True, null=True, verbose_name='امتیاز عملکرد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EmdadUser.customuser')),
            ],
            options={
                'verbose_name': 'پیگیری',
                'verbose_name_plural': 'پیگیری',
            },
        ),
        migrations.AddConstraint(
            model_name='order_product',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_product'),
        ),
    ]
