# Generated by Django 4.2.1 on 2023-05-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='location',
            new_name='address',
        ),
    ]
