# Generated by Django 4.2.1 on 2023-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_rename_location_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_cusotmer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه نهایی پرداخت شده توسط مشتری'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='total_expanse_agent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='خرجکرد نهایی پرداخت شده (تکنسین)'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='total_wage_agent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='اجرت نهایی پرداخت شده (تکنسین)'),
        ),
    ]
