# Generated by Django 4.2.1 on 2023-05-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmdadUser', '0002_remove_technecian_expertise'),
        ('Order', '0003_order_total_price_cusotmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='total_price_cusotmer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه نهایی پرداخت شده  (مشتری)'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='EmdadUser.customuser'),
        ),
    ]
