# Generated by Django 4.2.1 on 2023-05-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_alter_followup_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='created_date',
            new_name='time',
        ),
    ]
