# Generated by Django 4.2.1 on 2023-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emdad', '0003_alter_motor_technecians_alter_region_technecians_and_more'),
        ('Order', '0006_rename_created_date_followup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='motors',
            field=models.ManyToManyField(to='Emdad.motor', verbose_name='موتور'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='Emdad.service', verbose_name='خدمات'),
        ),
    ]
